export const setData = 'add-data'
export const errorData = 'error-data'
export const sortData = 'sort-data'
export const filterData = 'filter-data'
export const setPage = 'setPage'
export const setFilter = 'setFilter'
export const paginationQuantity = 'paginationQuantity'